% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Project 1: Olmypic History Trend Analytics},
  pdfauthor={Group 9 - Thomas George Thomas, Yang Liu, Pratyush Pothuneedi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Project 1: Olmypic History Trend Analytics}
\author{Group 9 - Thomas George Thomas, Yang Liu, Pratyush Pothuneedi}
\date{10/28/2021}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Importing Required packages}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(reshape2)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(gridExtra)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(data.table)}
\end{Highlighting}
\end{Shaded}

\hypertarget{data-acquisition}{%
\section{1. Data Acquisition}\label{data-acquisition}}

\hypertarget{importing-the-datasets}{%
\subsection{Importing the datasets}\label{importing-the-datasets}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Data of the athelets and countries}
\NormalTok{atheletes\_df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}athlete\_events.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =} \StringTok{\textquotesingle{},\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(atheletes\_df, }\DecValTok{5}\NormalTok{) }\CommentTok{\# structure of the dataset}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ID                     Name Sex Age Height Weight           Team NOC
## 1  1                A Dijiang   M  24    180     80          China CHN
## 2  2                 A Lamusi   M  23    170     60          China CHN
## 3  3      Gunnar Nielsen Aaby   M  24     NA     NA        Denmark DEN
## 4  4     Edgar Lindenau Aabye   M  34     NA     NA Denmark/Sweden DEN
## 5  5 Christine Jacoba Aaftink   F  21    185     82    Netherlands NED
##         Games Year Season      City         Sport
## 1 1992 Summer 1992 Summer Barcelona    Basketball
## 2 2012 Summer 2012 Summer    London          Judo
## 3 1920 Summer 1920 Summer Antwerpen      Football
## 4 1900 Summer 1900 Summer     Paris    Tug-Of-War
## 5 1988 Winter 1988 Winter   Calgary Speed Skating
##                              Event Medal
## 1      Basketball Men's Basketball  <NA>
## 2     Judo Men's Extra-Lightweight  <NA>
## 3          Football Men's Football  <NA>
## 4      Tug-Of-War Men's Tug-Of-War  Gold
## 5 Speed Skating Women's 500 metres  <NA>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Importing Data of the regions tied with the NOC code}
\NormalTok{regions\_df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}noc\_regions.csv\textquotesingle{}}\NormalTok{, }\AttributeTok{header=} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =}\StringTok{\textquotesingle{},\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(regions\_df, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   NOC      region                notes
## 1 AFG Afghanistan                     
## 2 AHO     Curacao Netherlands Antilles
## 3 ALB     Albania                     
## 4 ALG     Algeria                     
## 5 AND     Andorra
\end{verbatim}

\hypertarget{data-wrangling}{%
\section{2. Data Wrangling}\label{data-wrangling}}

\hypertarget{data-discovery}{%
\subsection{2.1 Data Discovery}\label{data-discovery}}

\hypertarget{a.-summary-statistics}{%
\subsubsection{A. Summary Statistics}\label{a.-summary-statistics}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(atheletes\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        ID             Name               Sex                 Age       
##  Min.   :     1   Length:271116      Length:271116      Min.   :10.00  
##  1st Qu.: 34643   Class :character   Class :character   1st Qu.:21.00  
##  Median : 68205   Mode  :character   Mode  :character   Median :24.00  
##  Mean   : 68249                                         Mean   :25.56  
##  3rd Qu.:102097                                         3rd Qu.:28.00  
##  Max.   :135571                                         Max.   :97.00  
##                                                         NA's   :9474   
##      Height          Weight          Team               NOC           
##  Min.   :127.0   Min.   : 25.0   Length:271116      Length:271116     
##  1st Qu.:168.0   1st Qu.: 60.0   Class :character   Class :character  
##  Median :175.0   Median : 70.0   Mode  :character   Mode  :character  
##  Mean   :175.3   Mean   : 70.7                                        
##  3rd Qu.:183.0   3rd Qu.: 79.0                                        
##  Max.   :226.0   Max.   :214.0                                        
##  NA's   :60171   NA's   :62875                                        
##     Games                Year         Season              City          
##  Length:271116      Min.   :1896   Length:271116      Length:271116     
##  Class :character   1st Qu.:1960   Class :character   Class :character  
##  Mode  :character   Median :1988   Mode  :character   Mode  :character  
##                     Mean   :1978                                        
##                     3rd Qu.:2002                                        
##                     Max.   :2016                                        
##                                                                         
##     Sport              Event              Medal          
##  Length:271116      Length:271116      Length:271116     
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character  
##                                                          
##                                                          
##                                                          
## 
\end{verbatim}

\textbf{We can see that there are NA's in the numerical fields of Age,
Height, Weight which we will handle}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(regions\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      NOC               region             notes          
##  Length:230         Length:230         Length:230        
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character
\end{verbatim}

\hypertarget{b.-discovering-discrete-data}{%
\subsubsection{B. Discovering Discrete
Data}\label{b.-discovering-discrete-data}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  atheletes\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{()),}
  \AttributeTok{caption =} \StringTok{"Total Records for Athletes Dataframe"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}r@{}}
\caption{Total Records for Athletes Dataframe}\tabularnewline
\toprule
total\_records \\
\midrule
\endfirsthead
\toprule
total\_records \\
\midrule
\endhead
271116 \\
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  regions\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{()),}
  \AttributeTok{caption =} \StringTok{"Total Records in Regions Dataframe"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}r@{}}
\caption{Total Records in Regions Dataframe}\tabularnewline
\toprule
total\_records \\
\midrule
\endfirsthead
\toprule
total\_records \\
\midrule
\endhead
230 \\
\bottomrule
\end{longtable}

Looking for NA's in all the columns

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Store the cols with missing values }
\NormalTok{list\_na }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(atheletes\_df)[}\FunctionTok{apply}\NormalTok{(atheletes\_df, }\DecValTok{2}\NormalTok{, anyNA)]}
\NormalTok{list\_na}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Age"    "Height" "Weight" "Medal"
\end{verbatim}

We have NA's for numerical data: Age, Height \& Weight and for
categorical data: Medal.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  atheletes\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Medal) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{())}
\NormalTok{    ,}\AttributeTok{caption=}\StringTok{"Records by Medal Count"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Records by Medal Count}\tabularnewline
\toprule
Medal & total\_records \\
\midrule
\endfirsthead
\toprule
Medal & total\_records \\
\midrule
\endhead
Bronze & 13295 \\
Gold & 13372 \\
Silver & 13116 \\
NA & 231333 \\
\bottomrule
\end{longtable}

\textbf{There are 231333 NA's for Medals which is categorical data and
we need to handle this in the cleaning part}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#looking for NA\textquotesingle{}s in regions\_df}
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  regions\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(NOC,region,notes) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Total\_records=}\FunctionTok{n}\NormalTok{()),}
  \AttributeTok{caption=}\StringTok{"Records grouped by categories"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'NOC', 'region'. You can override using the `.groups` argument.
\end{verbatim}

\begin{longtable}[]{@{}lllr@{}}
\caption{Records grouped by categories}\tabularnewline
\toprule
NOC & region & notes & Total\_records \\
\midrule
\endfirsthead
\toprule
NOC & region & notes & Total\_records \\
\midrule
\endhead
ROT & NA & Refugee Olympic Team & 1 \\
TUV & NA & Tuvalu & 1 \\
UNK & NA & Unknown & 1 \\
\bottomrule
\end{longtable}

No NA's in region\_df

\hypertarget{structuring}{%
\subsection{2.2 Structuring}\label{structuring}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(atheletes\_df,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ID                     Name Sex Age Height Weight           Team NOC
## 1  1                A Dijiang   M  24    180     80          China CHN
## 2  2                 A Lamusi   M  23    170     60          China CHN
## 3  3      Gunnar Nielsen Aaby   M  24     NA     NA        Denmark DEN
## 4  4     Edgar Lindenau Aabye   M  34     NA     NA Denmark/Sweden DEN
## 5  5 Christine Jacoba Aaftink   F  21    185     82    Netherlands NED
##         Games Year Season      City         Sport
## 1 1992 Summer 1992 Summer Barcelona    Basketball
## 2 2012 Summer 2012 Summer    London          Judo
## 3 1920 Summer 1920 Summer Antwerpen      Football
## 4 1900 Summer 1900 Summer     Paris    Tug-Of-War
## 5 1988 Winter 1988 Winter   Calgary Speed Skating
##                              Event Medal
## 1      Basketball Men's Basketball  <NA>
## 2     Judo Men's Extra-Lightweight  <NA>
## 3          Football Men's Football  <NA>
## 4      Tug-Of-War Men's Tug-Of-War  Gold
## 5 Speed Skating Women's 500 metres  <NA>
\end{verbatim}

\textbf{We can see that we don't need to do additional restructuring as
columns like ``Games'' is already split and available as Year and
Season}

\hypertarget{cleaning}{%
\subsection{2.3 Cleaning}\label{cleaning}}

\hypertarget{a.-handling-missing-data}{%
\subsubsection{A. Handling Missing
Data}\label{a.-handling-missing-data}}

We can't filter out the NA values since the columns that exhibit them
are required for our analysis. We will be filling the NA values for
numerical columns like Age, Height, Weight with the \textbf{median}
values since we require whole numbers. The Medals are filled with
\textbf{`None'} which would signify that the athletes simply didn't win
any of the categories of Medals (Gold, Silver, Bronze).

\textbf{We didn't filter out the NA records in Age, Height and Weight
because that would mean that crucial data would be dropped leading to
data skewness, we are using the Median values since we require whole
numbers and to reduce the degree of skewness while maintaining data
integrity.}

\hypertarget{b.-replacing-nas-in-medals}{%
\paragraph{B. Replacing NA's in
Medals}\label{b.-replacing-nas-in-medals}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{atheletes\_df}\SpecialCharTok{$}\NormalTok{Medal }\OtherTok{\textless{}{-}}\NormalTok{ atheletes\_df}\SpecialCharTok{$}\NormalTok{Medal }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{replace\_na}\NormalTok{(}\StringTok{"None"}\NormalTok{) }\CommentTok{\# It is assumed tha the athlete participated in the sport but didn\textquotesingle{}t win a medal}
\end{Highlighting}
\end{Shaded}

Calculating Missing Median for the missing values for Age, Height and
Weight

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{list\_na }\OtherTok{\textless{}{-}}\NormalTok{ list\_na[ list\_na }\SpecialCharTok{!=}\StringTok{"Medal"}\NormalTok{]}

\CommentTok{\# Calculate median for the missing values}
\NormalTok{missing\_median }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(atheletes\_df[,}\FunctionTok{colnames}\NormalTok{(atheletes\_df) }\SpecialCharTok{\%in\%}\NormalTok{ list\_na],}
      \DecValTok{2}\NormalTok{, }\CommentTok{\# 2 is for Columns}
\NormalTok{      median,}
      \AttributeTok{na.rm =}  \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{missing\_median}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Age Height Weight 
##     24    175     70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Replace the missing values with median}
\NormalTok{atheletes\_df }\OtherTok{\textless{}{-}}\NormalTok{ atheletes\_df }\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{mutate}\NormalTok{(}
     \AttributeTok{Age  =} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Age), missing\_median[}\DecValTok{1}\NormalTok{], Age),}
     \AttributeTok{Height =} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Height), missing\_median[}\DecValTok{2}\NormalTok{], Height),}
     \AttributeTok{Weight =} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Weight), missing\_median[}\DecValTok{3}\NormalTok{], Weight)}
\NormalTok{   )}
\end{Highlighting}
\end{Shaded}

\hypertarget{c.-handling-missing-data-in-regions}{%
\paragraph{C. Handling Missing data in
Regions}\label{c.-handling-missing-data-in-regions}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Replacing Na\textquotesingle{}s with the respective region/notes for the NOC\textquotesingle{}s}
\NormalTok{regions\_df}\SpecialCharTok{$}\NormalTok{region }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(regions\_df}\SpecialCharTok{$}\NormalTok{region), regions\_df}\SpecialCharTok{$}\NormalTok{notes, regions\_df}\SpecialCharTok{$}\NormalTok{region)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  regions\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{())}
\NormalTok{  ,}\AttributeTok{caption =} \StringTok{"Number of NA\textquotesingle{}s in Region after fix"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Number of NA's in Region after fix}\tabularnewline
\toprule
region & total\_records \\
\midrule
\endfirsthead
\toprule
region & total\_records \\
\midrule
\endhead
\bottomrule
\end{longtable}

\hypertarget{enriching}{%
\subsection{2.4 Enriching}\label{enriching}}

\hypertarget{a.-adding-attribute-region}{%
\subsubsection{A. Adding Attribute
region}\label{a.-adding-attribute-region}}

We will join regions\_df and atheletes\_df based on the NOC code to get
the Region for enriching the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{athletes }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(atheletes\_df, regions\_df, }\AttributeTok{by=}\StringTok{"NOC"}\NormalTok{)}

\CommentTok{\# Replacing Region with Country to make the data more meaningful}
\FunctionTok{colnames}\NormalTok{(athletes)[}\FunctionTok{which}\NormalTok{(}\FunctionTok{names}\NormalTok{(athletes) }\SpecialCharTok{==} \StringTok{"region"}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"Region"} 
\CommentTok{\# Removing notes since it\textquotesingle{}s not relevant to our analysis anymore}
\NormalTok{athletes }\OtherTok{\textless{}{-}}\NormalTok{ athletes[,}\SpecialCharTok{{-}}\DecValTok{17}\NormalTok{]}
\FunctionTok{head}\NormalTok{(athletes,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ID                     Name Sex Age Height Weight           Team NOC
## 1  1                A Dijiang   M  24    180     80          China CHN
## 2  2                 A Lamusi   M  23    170     60          China CHN
## 3  3      Gunnar Nielsen Aaby   M  24    175     70        Denmark DEN
## 4  4     Edgar Lindenau Aabye   M  34    175     70 Denmark/Sweden DEN
## 5  5 Christine Jacoba Aaftink   F  21    185     82    Netherlands NED
##         Games Year Season      City         Sport
## 1 1992 Summer 1992 Summer Barcelona    Basketball
## 2 2012 Summer 2012 Summer    London          Judo
## 3 1920 Summer 1920 Summer Antwerpen      Football
## 4 1900 Summer 1900 Summer     Paris    Tug-Of-War
## 5 1988 Winter 1988 Winter   Calgary Speed Skating
##                              Event Medal      Region
## 1      Basketball Men's Basketball  None       China
## 2     Judo Men's Extra-Lightweight  None       China
## 3          Football Men's Football  None     Denmark
## 4      Tug-Of-War Men's Tug-Of-War  Gold     Denmark
## 5 Speed Skating Women's 500 metres  None Netherlands
\end{verbatim}

\textbf{We don't have any other attribute to split or to create a new
category since we believe that we have all the required columns for our
analysis}

\hypertarget{validating}{%
\subsection{2.5 Validating}\label{validating}}

\hypertarget{a.-check-for-any-missing-values}{%
\subsubsection{A. Check for any missing
values}\label{a.-check-for-any-missing-values}}

\begin{Shaded}
\begin{Highlighting}[]
 \CommentTok{\# Counting the number of NA\textquotesingle{}s for all the columns}
 \FunctionTok{colnames}\NormalTok{(athletes)[}\FunctionTok{apply}\NormalTok{(athletes, }\DecValTok{2}\NormalTok{, anyNA)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Region"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
\NormalTok{  athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(NOC,Region)  }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(NOC,Region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{())}
\NormalTok{    ,}\AttributeTok{caption=}\StringTok{"Null Records check by Medal Count"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'NOC'. You can override using the `.groups` argument.
\end{verbatim}

\begin{longtable}[]{@{}llr@{}}
\caption{Null Records check by Medal Count}\tabularnewline
\toprule
NOC & Region & total\_records \\
\midrule
\endfirsthead
\toprule
NOC & Region & total\_records \\
\midrule
\endhead
SGP & NA & 349 \\
\bottomrule
\end{longtable}

\textbf{For NOC SGP, there are no records in our regions\_df but is
present in atheltes\_df, as a result we are getting NA values after the
join. We will add Singapore Region to the NOC in the joined data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{athletes}\SpecialCharTok{$}\NormalTok{Region }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{((}\FunctionTok{is.na}\NormalTok{(athletes}\SpecialCharTok{$}\NormalTok{Region) }\SpecialCharTok{\&}\NormalTok{ athletes}\SpecialCharTok{$}\NormalTok{NOC}\SpecialCharTok{==}\StringTok{\textquotesingle{}SGP\textquotesingle{}}\NormalTok{), }\StringTok{"Singapore"}\NormalTok{, athletes}\SpecialCharTok{$}\NormalTok{Region)}


\FunctionTok{kable}\NormalTok{(}
\NormalTok{  athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(Region)  }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(Region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_records=}\FunctionTok{n}\NormalTok{())}
\NormalTok{    ,}\AttributeTok{caption=}\StringTok{"Checking for NA records in Region after change"}
  
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Checking for NA records in Region after change}\tabularnewline
\toprule
Region & total\_records \\
\midrule
\endfirsthead
\toprule
Region & total\_records \\
\midrule
\endhead
\bottomrule
\end{longtable}

\hypertarget{b.-check-for-duplicates}{%
\subsubsection{B. Check for Duplicates}\label{b.-check-for-duplicates}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(athletes))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1385
\end{verbatim}

\textbf{There 1385 duplicate records on the whole data set}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Removing the duplicates}
\NormalTok{athletes }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(athletes)}
\end{Highlighting}
\end{Shaded}

\hypertarget{c.-checking-boundary-cases}{%
\subsubsection{C. Checking boundary
cases}\label{c.-checking-boundary-cases}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{ (}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}\AttributeTok{max\_age=}\FunctionTok{max}\NormalTok{(Age), }\AttributeTok{min\_age=}\FunctionTok{min}\NormalTok{(Age), }\AttributeTok{Average\_Age=}\FunctionTok{mean}\NormalTok{(Age)),}
\AttributeTok{caption=}\StringTok{"Age boundary cases"}

\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rrr@{}}
\caption{Age boundary cases}\tabularnewline
\toprule
max\_age & min\_age & Average\_Age \\
\midrule
\endfirsthead
\toprule
max\_age & min\_age & Average\_Age \\
\midrule
\endhead
97 & 10 & 25.40454 \\
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{ (}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}\AttributeTok{max\_height=}\FunctionTok{max}\NormalTok{(Height), }\AttributeTok{min\_height=}\FunctionTok{min}\NormalTok{(Height), }\AttributeTok{Average\_height=}\FunctionTok{mean}\NormalTok{(Height)),}
\AttributeTok{caption=}\StringTok{"Height boundary cases"}

\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rrr@{}}
\caption{Height boundary cases}\tabularnewline
\toprule
max\_height & min\_height & Average\_height \\
\midrule
\endfirsthead
\toprule
max\_height & min\_height & Average\_height \\
\midrule
\endhead
226 & 127 & 175.265 \\
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{ (}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}\AttributeTok{max\_weight=}\FunctionTok{max}\NormalTok{(Weight), }\AttributeTok{min\_weigt=}\FunctionTok{min}\NormalTok{(Weight), }\AttributeTok{Average\_weight=}\FunctionTok{mean}\NormalTok{(Weight)),}
\AttributeTok{caption=}\StringTok{"Weight boundary cases"}

\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rrr@{}}
\caption{Weight boundary cases}\tabularnewline
\toprule
max\_weight & min\_weigt & Average\_weight \\
\midrule
\endfirsthead
\toprule
max\_weight & min\_weigt & Average\_weight \\
\midrule
\endhead
214 & 25 & 70.5417 \\
\bottomrule
\end{longtable}

All our boundary cases looks reasonable and accurate.

\hypertarget{publishing}{%
\subsection{2.6 Publishing}\label{publishing}}

The data is cleaned \& wrangled and made available for the team to
develop business cases.

\hypertarget{analytical-questions}{%
\section{3. Analytical Questions}\label{analytical-questions}}

\hypertarget{trend-analysis-of-top-10-regions-with-the-highest-number-of-medals-between-1896---1956-1957---2016}{%
\subsubsection{1. Trend analysis of Top 10 regions with the highest
number of medals between 1896 - 1956 \& 1957 -
2016}\label{trend-analysis-of-top-10-regions-with-the-highest-number-of-medals-between-1896---1956-1957---2016}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p1 }\OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Medal}\SpecialCharTok{!=}\StringTok{\textquotesingle{}None\textquotesingle{}} \SpecialCharTok{\&}\NormalTok{ Year}\SpecialCharTok{\textless{}=}\DecValTok{1956}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total\_medals=}\FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total\_medals))  }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Region=}\FunctionTok{factor}\NormalTok{(Region, }\AttributeTok{levels=}\NormalTok{Region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{( }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Region, }\AttributeTok{y=}\NormalTok{total\_medals))}\SpecialCharTok{+}
    \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}  
    \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Number of Medals"}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Top 10 Regions with highest Medals from 1896 {-} 1956"}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}

\NormalTok{p2 }\OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Medal}\SpecialCharTok{!=}\StringTok{\textquotesingle{}None\textquotesingle{}} \SpecialCharTok{\&}\NormalTok{ Year}\SpecialCharTok{\textgreater{}}\DecValTok{1956}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{total\_medals=}\FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total\_medals))  }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Region=}\FunctionTok{factor}\NormalTok{(Region, }\AttributeTok{levels=}\NormalTok{Region)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{( }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Region, }\AttributeTok{y=}\NormalTok{total\_medals))}\SpecialCharTok{+}
    \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}  
    \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Number of Medals"}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Top 10 Regions with highest Medals from 1957 {-} 2016"}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}

\FunctionTok{grid.arrange}\NormalTok{(p1, p2, }\AttributeTok{ncol=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Olympic-History_files/figure-latex/unnamed-chunk-23-1} \end{center}

\textbf{Observation}: USA remains the region with the highest number of
Medals in the combined history of 120 years in Olympics. Russia, a new
inclusion in the top 10 took 2nd position in the later half.Germany
moved into the 3rd position in the second half while UK and France
slipped from 2nd and 3rd to 8th and 9th position. There are new
countries in the later half such as Australia, Canada and Japan which
where not in the top 10 for the earlier history of Olympics.

\hypertarget{medals-won-by-malesfemales-over-time}{%
\subsubsection{2. Medals won by Males/Females over
Time}\label{medals-won-by-malesfemales-over-time}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(Medal}\SpecialCharTok{!=}\StringTok{\textquotesingle{}None\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(Year, Sex) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{Total\_Medals =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(., }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Year, }\AttributeTok{y=}\NormalTok{Total\_Medals, }\AttributeTok{group=}\NormalTok{Sex, }\AttributeTok{color=}\NormalTok{Sex))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size=}\DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{()  }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values=}\FunctionTok{c}\NormalTok{(}\StringTok{"darkblue"}\NormalTok{,}\StringTok{"red"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Medals won by Male/Female over Time"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Year'. You can override using the `.groups` argument.
\end{verbatim}

\includegraphics{Olympic-History_files/figure-latex/unnamed-chunk-24-1.pdf}

\textbf{Observation:} From the graph, we can see that there is a gradual
increase in the number of medals won by female athletes over time. Male
athletes tend to outnumber female athletes but their numbers also keep
fluctuating over time. After the years 1994, the summer and winter
Olympic games were split and held during seperate years, hence why the
graph shows different points.

\hypertarget{finding-the-most-participated-sport-in-olympics-every-year}{%
\subsubsection{3. Finding the most participated sport in Olympics every
year}\label{finding-the-most-participated-sport-in-olympics-every-year}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q3}\OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(Year, Sport) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarize}\NormalTok{(}\AttributeTok{Participation =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(Year,}\FunctionTok{desc}\NormalTok{(Participation))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Year'. You can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  q3 }\OtherTok{\textless{}{-}}\NormalTok{ q3[}\SpecialCharTok{!}\FunctionTok{duplicated}\NormalTok{(q3}\SpecialCharTok{$}\NormalTok{Year),] }\CommentTok{\# Taking only the first record}
  
  \FunctionTok{kable}\NormalTok{(}
\NormalTok{  q3,}
  \AttributeTok{caption=}\StringTok{"Most participated Sport in Olympic Games every year"}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rlr@{}}
\caption{Most participated Sport in Olympic Games every
year}\tabularnewline
\toprule
Year & Sport & Participation \\
\midrule
\endfirsthead
\toprule
Year & Sport & Participation \\
\midrule
\endhead
1896 & Athletics & 106 \\
1900 & Fencing & 317 \\
1904 & Gymnastics & 458 \\
1906 & Athletics & 470 \\
1908 & Athletics & 778 \\
1912 & Athletics & 962 \\
1920 & Athletics & 849 \\
1924 & Athletics & 1003 \\
1928 & Athletics & 992 \\
1932 & Art Competitions & 620 \\
1936 & Athletics & 1007 \\
1948 & Gymnastics & 1060 \\
1952 & Gymnastics & 2391 \\
1956 & Athletics & 1013 \\
1960 & Gymnastics & 1746 \\
1964 & Gymnastics & 1484 \\
1968 & Gymnastics & 1496 \\
1972 & Athletics & 1686 \\
1976 & Athletics & 1297 \\
1980 & Athletics & 1268 \\
1984 & Athletics & 1674 \\
1988 & Athletics & 2062 \\
1992 & Athletics & 2054 \\
1994 & Cross Country Skiing & 639 \\
1996 & Athletics & 2386 \\
1998 & Cross Country Skiing & 733 \\
2000 & Athletics & 2468 \\
2002 & Cross Country Skiing & 774 \\
2004 & Athletics & 2175 \\
2006 & Cross Country Skiing & 812 \\
2008 & Athletics & 2244 \\
2010 & Cross Country Skiing & 725 \\
2012 & Athletics & 2278 \\
2014 & Cross Country Skiing & 765 \\
2016 & Athletics & 2508 \\
\bottomrule
\end{longtable}

\textbf{Observation}: This table shows that Athletics has remained the
most contested sport in 120 years of Olympics. Art Competitions were the
highest participated Olympic Sport in 1932 before it was removed from
the Olympics. As the Olympic Winter and Summer games were seperated into
different years from 1994, Cros Country Skiing emerged as the most
participated game held during the Winters.

\hypertarget{in-which-olympic-year-did-a-particular-country-win-a-medal-for-the-first-time-for-a-particular-sport}{%
\subsubsection{4. In which Olympic year did a particular country win a
medal for the first time for a particular
sport}\label{in-which-olympic-year-did-a-particular-country-win-a-medal-for-the-first-time-for-a-particular-sport}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Ans1 }\OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{filter}\NormalTok{(Sport}\SpecialCharTok{==}\StringTok{"Football"}\NormalTok{,Medal}\SpecialCharTok{!=}\StringTok{"None"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{select}\NormalTok{(Region,Year) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Region,Year) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}\AttributeTok{Year=}\FunctionTok{min}\NormalTok{(Year))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Region'. You can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Ans1 }\OtherTok{\textless{}{-}}\NormalTok{ Ans1[}\SpecialCharTok{!}\FunctionTok{duplicated}\NormalTok{(Ans1}\SpecialCharTok{$}\NormalTok{Region),]}

\FunctionTok{kable}\NormalTok{ (}
\NormalTok{  Ans1,}
  \AttributeTok{caption=}\StringTok{"First year in which countries won medal in Football"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{First year in which countries won medal in
Football}\tabularnewline
\toprule
Region & Year \\
\midrule
\endfirsthead
\toprule
Region & Year \\
\midrule
\endhead
Argentina & 1928 \\
Austria & 1936 \\
Belgium & 1900 \\
Brazil & 1984 \\
Bulgaria & 1956 \\
Cameroon & 2000 \\
Canada & 1904 \\
Chile & 2000 \\
China & 1996 \\
Czech Republic & 1964 \\
Denmark & 1906 \\
France & 1900 \\
Germany & 1964 \\
Ghana & 1992 \\
Greece & 1906 \\
Hungary & 1952 \\
Italy & 1928 \\
Japan & 1968 \\
Mexico & 2012 \\
Netherlands & 1900 \\
Nigeria & 1996 \\
Norway & 1936 \\
Paraguay & 2004 \\
Poland & 1972 \\
Russia & 1956 \\
Serbia & 1948 \\
South Korea & 2012 \\
Spain & 1920 \\
Sweden & 1924 \\
Switzerland & 1924 \\
UK & 1900 \\
Uruguay & 1924 \\
USA & 1904 \\
\bottomrule
\end{longtable}

\textbf{Observation:} From the above table we can see the first year in
which each country won a medal for football. The first countries to win
medals for football are UK,Belgium,France and Netherlands and all these
countries are from Europe.

\hypertarget{trend-analysis-per-sport-per-country-for-the-gap-between-medals-for-football}{%
\subsubsection{5. Trend analysis per sport per country for the gap
between medals for
Football}\label{trend-analysis-per-sport-per-country-for-the-gap-between-medals-for-football}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{filter}\NormalTok{(Sport}\SpecialCharTok{==}\StringTok{"Football"}\NormalTok{,Medal}\SpecialCharTok{!=}\StringTok{"None"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{select}\NormalTok{(Region, Year) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}\AttributeTok{Number\_of\_Years=}\FunctionTok{max}\NormalTok{(Year)}\SpecialCharTok{{-}}\FunctionTok{min}\NormalTok{(Year)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Number\_of\_Years)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{Region=}\FunctionTok{factor}\NormalTok{(Region, }\AttributeTok{levels=}\NormalTok{Region)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{( }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Region, }\AttributeTok{x=}\NormalTok{Number\_of\_Years))}\SpecialCharTok{+}
\FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"orange"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
\CommentTok{\#labs(y="Region")+}
\FunctionTok{xlab}\NormalTok{(}\StringTok{"Number of Years"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Gap between medals for countries for Football"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Olympic-History_files/figure-latex/unnamed-chunk-27-1.pdf}

\textbf{Observation:} The gap between first and last medals for football
for each country is displayed. Canada has the largest gap of 112 years
while Czech Republic has the smallest gap of 16 years.

\hypertarget{comparison-of-medals-won-by-regions-in-summer-winter.}{%
\subsubsection{6. Comparison of medals won by regions in Summer \&
Winter.}\label{comparison-of-medals-won-by-regions-in-summer-winter.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Ans3}\FloatTok{.1} \OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{filter}\NormalTok{(Medal}\SpecialCharTok{!=}\StringTok{\textquotesingle{}None\textquotesingle{}}\NormalTok{,Season}\SpecialCharTok{==}\StringTok{"Summer"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarize}\NormalTok{(}\AttributeTok{number\_of\_medals=}\FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(number\_of\_medals)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{Region=}\FunctionTok{factor}\NormalTok{(Region, }\AttributeTok{levels=}\NormalTok{Region)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{( }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Region, }\AttributeTok{x=}\NormalTok{number\_of\_medals))}\SpecialCharTok{+}
\FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"green"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
\CommentTok{\#labs(y="Region")+}
\FunctionTok{xlab}\NormalTok{(}\StringTok{"Medals"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Number of medals won by countries in Summer"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}

\NormalTok{Ans3}\FloatTok{.2} \OtherTok{\textless{}{-}}
\NormalTok{athletes }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{filter}\NormalTok{(Medal}\SpecialCharTok{!=}\StringTok{\textquotesingle{}None\textquotesingle{}}\NormalTok{,Season}\SpecialCharTok{==}\StringTok{"Winter"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(Region) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarize}\NormalTok{(}\AttributeTok{number\_of\_medals=}\FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(number\_of\_medals)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{Region=}\FunctionTok{factor}\NormalTok{(Region, }\AttributeTok{levels=}\NormalTok{Region)) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{20}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ggplot}\NormalTok{( }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Region, }\AttributeTok{x=}\NormalTok{number\_of\_medals))}\SpecialCharTok{+}
\FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"purple"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
\CommentTok{\#labs(y="Region")+}
\FunctionTok{xlab}\NormalTok{(}\StringTok{"Medals"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Number of medals won by countries in Winter"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}

\FunctionTok{grid.arrange}\NormalTok{(Ans3}\FloatTok{.1}\NormalTok{,Ans3}\FloatTok{.2}\NormalTok{,}\AttributeTok{ncol=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Olympic-History_files/figure-latex/unnamed-chunk-28-1.pdf}

\textbf{Observation:} In Summer USA takes the top spot in the number of
medals won and Russia stood second. When it comes to winter the
positions are interchanged. Germany remains constant in both summer and
winter. The graph has a uniform increase in the number of medals in
summer but its not a uniform increase in winter, So this means that the
winter games are more competitive while summer has a distinctive winner.

\hypertarget{top-10-host-cities-with-the-highest-participation.}{%
\subsubsection{7. Top 10 Host cities with the highest
participation.}\label{top-10-host-cities-with-the-highest-participation.}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Top 10 Host cities with highest participation.}
\NormalTok{Top10 }\OtherTok{\textless{}{-}}
\NormalTok{  athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(Year,City) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Year,City) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{number=}\FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(number))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Year'. You can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{head}\NormalTok{(Top10, }\DecValTok{10}\NormalTok{)}
\NormalTok{  ,}\AttributeTok{caption=}\NormalTok{(}\StringTok{"Host cities with highest participation"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}rlr@{}}
\caption{Host cities with highest participation}\tabularnewline
\toprule
Year & City & number \\
\midrule
\endfirsthead
\toprule
Year & City & number \\
\midrule
\endhead
2000 & Sydney & 13821 \\
1996 & Atlanta & 13780 \\
2016 & Rio de Janeiro & 13688 \\
2008 & Beijing & 13602 \\
2004 & Athina & 13443 \\
1992 & Barcelona & 12977 \\
2012 & London & 12920 \\
1988 & Seoul & 12037 \\
1972 & Munich & 10304 \\
1984 & Los Angeles & 9454 \\
\bottomrule
\end{longtable}

\textbf{Observation:} The top ten cities with the highest participation
are Sydney(2000), Atlanta(1996), Rio de Janeiro(2016),Beijing(2008),
Athina(2004), Barcelona(1992), London(2012),Seoul(1988),Munich(1972),Los
Angeles(1984)

\hypertarget{top-10-athletes-with-the-highest-participation-in-the-olympics}{%
\subsubsection{8. Top 10 athletes with the highest participation in the
Olympics}\label{top-10-athletes-with-the-highest-participation-in-the-olympics}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#}
\NormalTok{Top10a }\OtherTok{\textless{}{-}}
\NormalTok{    athletes }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(Name) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Name) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarize}\NormalTok{(}\AttributeTok{number=}\FunctionTok{n}\NormalTok{())  }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(number)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice}\NormalTok{(}\DecValTok{0}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(Top10a, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Name, }\AttributeTok{y=}\NormalTok{number))}\SpecialCharTok{+}
\FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{fill=}\StringTok{"gold"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
\FunctionTok{labs}\NormalTok{(}\AttributeTok{y=}\StringTok{"Number of Olympics "}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{xlab}\NormalTok{(}\StringTok{"Athletes"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{theme}\NormalTok{(}\AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Top 10 most participated athlete in the Olympics"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{0}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{flushleft}\includegraphics{Olympic-History_files/figure-latex/unnamed-chunk-30-1} \end{flushleft}

\textbf{Observation:} As we can see nearly all the top 10 athletes
participated in the Olympics more than 30 times and the one with the
most is Heikki Ilmari Savolainen with 39 times

\hypertarget{athletes-with-the-most-number-of-medals-in-each-sport}{%
\subsubsection{9. Athletes with the most number of medals in each
sport}\label{athletes-with-the-most-number-of-medals-in-each-sport}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\#Athlete with the most number of medals per sport}
\NormalTok{df }\OtherTok{\textless{}{-}} 
\NormalTok{   athletes }\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{filter}\NormalTok{( Medal }\SpecialCharTok{!=} \StringTok{\textquotesingle{}None\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{select}\NormalTok{(Name,Sport)}\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{group\_by}\NormalTok{(Name,Sport) }\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{summarize}\NormalTok{(}\AttributeTok{number=}\FunctionTok{n}\NormalTok{())  }\SpecialCharTok{\%\textgreater{}\%}
   \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(number)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'Name'. You can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dfuevent }\OtherTok{\textless{}{-}}\NormalTok{ df[}\SpecialCharTok{!}\FunctionTok{duplicated}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Sport),]}
 
\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{head}\NormalTok{(dfuevent,}\DecValTok{11}\NormalTok{)}
\NormalTok{  ,}\AttributeTok{caption=}\NormalTok{(}\StringTok{"Athlete with the most number of medals per sport"}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llr@{}}
\caption{Athlete with the most number of medals per
sport}\tabularnewline
\toprule
Name & Sport & number \\
\midrule
\endfirsthead
\toprule
Name & Sport & number \\
\midrule
\endhead
Michael Fred Phelps, II & Swimming & 28 \\
Larysa Semenivna Latynina (Diriy-) & Gymnastics & 18 \\
Edoardo Mangiarotti & Fencing & 13 \\
Ole Einar Bjrndalen & Biathlon & 13 \\
Birgit Fischer-Schmidt & Canoeing & 12 \\
Paavo Johannes Nurmi & Athletics & 12 \\
Carl Townsend Osburn & Shooting & 11 \\
Gerard Theodor Hubert Van Innis & Archery & 10 \\
Isabelle Regina Werth & Equestrianism & 10 \\
Marit Bjrgen & Cross Country Skiing & 10 \\
Yang Yang & Short Track Speed Skating & 10 \\
\bottomrule
\end{longtable}

\textbf{Observation:} For Swimming, Michael Fred Phelps, II won the most
number of medals(28) and there are 11 players with the number of medals
equal or more than 10 in different sports.

\end{document}
