---
title: "project1"
author: "Yang Liu"
date: "10/29/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(reshape2)
library(dplyr)
library(knitr)
library(ggplot2)
```

```{r}
# 1. Data Acquisition
## Importing the datasets
# Data of the athelets and countries
atheletes_df <- read.csv('athlete_events.csv', header = TRUE, sep = ',')
head(atheletes_df, 5) # structure of the dataset
```

```{r}
# Importing Data of the regions tied with the NOC code
regions_df <- read.csv('noc_regions.csv', header= TRUE, sep =',')
head(regions_df, 5)
```

```{r}
# 2. Data Wrangling

## 2.1 Data Discovery

### A. Summary Statistics

summary(atheletes_df)
```

```{r}
summary(regions_df)
```

```{r}
kable(
  atheletes_df %>%
    summarise(total_records=n()),
  caption = "Total Records for Athletes Dataframe"
)
```

```{r}
kable(
  regions_df %>%
    summarise(total_records=n()),
  caption = "Total Records in Regions Dataframe"
  
)
```

```{r}
# Store the cols with missing values 
list_na <- colnames(atheletes_df)[apply(atheletes_df, 2, anyNA)]
list_na
```

```{r}
kable(
  atheletes_df %>%
    group_by(Medal) %>%
    summarise(total_records=n())
    ,caption="Records by Medal Count"
  
)
```

```{r}
#looking for NA's in regions_df
kable(
  regions_df %>%
    filter(is.na(region)) %>%
    group_by(NOC,region,notes) %>%
  summarise(Total_records=n()),
  caption="Records grouped by categories"
)
```

```{r}
head(atheletes_df,5)
```

```{r}
atheletes_df$Medal <- atheletes_df$Medal %>% 
  replace_na("None") # It is assumed tha the athlete participated in the sport but didn't win a medal
```

```{r}
list_na <- list_na[ list_na !="Medal"]
# Calculate median for the missing values
missing_median <- apply(atheletes_df[,colnames(atheletes_df) %in% list_na],
      2, # 2 is for Columns
      median,
      na.rm =  TRUE)
missing_median
```

```{r}
# Replace the missing values with median
atheletes_df <- atheletes_df %>%
   mutate(
     Age  = ifelse(is.na(Age), missing_median[1], Age),
     Height = ifelse(is.na(Height), missing_median[2], Height),
     Weight = ifelse(is.na(Weight), missing_median[3], Weight)
   )
```

```{r}
# Replacing Na's with the respective region/notes for the NOC's
regions_df$region <- ifelse(is.na(regions_df$region), regions_df$notes, regions_df$region)
```

```{r}
kable(
  regions_df %>%
    filter(is.na(region)) %>%
    summarise(total_records=n())
  ,caption = "Number of NA's in Region after fix"
  
)
```

```{r}
athletes <- left_join(atheletes_df, regions_df, by="NOC")

# Replacing Region with Country to make the data more meaningful
colnames(athletes)[which(names(athletes) == "region")] <- "Region" 
# Removing notes since it's not relevant to our analysis anymore
athletes <- athletes[,-17]
head(athletes,5)
```

```{r}
# Counting the number of NA's for all the columns
 colnames(athletes)[apply(athletes, 2, anyNA)]
kable(
  athletes %>%
    select(NOC,Region)  %>%
    filter(is.na(Region)) %>%
    group_by(NOC,Region) %>%
    summarise(total_records=n())
    ,caption="Null Records check by Medal Count"
)
```

```{r}
athletes$Region <- ifelse(is.na(athletes$Region) && athletes$NOC=='SGP', "Singapore", athletes$Region)
kable(
  athletes %>%
    select(Region)  %>%
    filter(is.na(Region)) %>%
    group_by(Region) %>%
    summarise(total_records=n())
    ,caption="Checking for NA records in Region after change"
  
)
```

```{r}
sum(duplicated(athletes))
```

```{r}
# Removing the duplicates
athletes <- unique(athletes)
```

```{r}
kable (
athletes %>%
summarise(max_age=max(Age), min_age=min(Age), Average_Age=mean(Age)),
caption="Age boundary cases"
)
kable (
athletes %>%
summarise(max_height=max(Height), min_height=min(Height), Average_height=mean(Height)),
caption="Height boundary cases"
)
kable (
athletes %>%
summarise(max_weight=max(Weight), min_weigt=min(Weight), Average_weight=mean(Weight)),
caption="Weight boundary cases"
)
```

```{r}

##Top 10 host cities with highest participation.
Top10 <-
  athletes %>%
    select(Year,City) %>%
    group_by(Year,City) %>%
    summarize(number=n())  %>%
    arrange(desc(number)) 

kable(
  Top10 
  ,caption=("Top 10 host cities with highest participation")
)


```

```{r fig.width=15}
##Top 10 most participated athlete in the Olympics
Top10a <-
    athletes %>%
    select(Name) %>%
    group_by(Name) %>%
    summarize(number=n())  %>%
    arrange(desc(number)) %>%
    slice(0:10)

ggplot(Top10a, aes(x=Name, y=number))+
geom_col(fill="gold") +
theme_minimal()+
labs(y="Number of Olympics ")+
xlab("athlete")+
theme(plot.title = element_text(hjust = 0.5)) +
ggtitle("Top 10 most participated athlete in the Olympics")+
geom_vline(xintercept = 0)+
geom_hline(yintercept = 0)

```

```{r}
###Athlete with the most number of medals per sport
df <- 
   athletes%>%
   filter( Medal != 'None') %>%
   select(Name,Sport)%>%
   group_by(Name,Sport) %>%
   summarize(number=n())  %>%
   arrange(desc(number)) 

dfuevent <- df[!duplicated(df$Sport),]
 
kable(
  dfuevent
  ,caption=("Athlete with the most number of medals per sport")
  )
```

